import type { EpisodeManifest } from "./types";

export const episodeManifest: EpisodeManifest = {
  mode: "remotion-only",
  episodeId: "demo",
  title: "别让视频前 5 秒空掉",
  seriesName: "Video Growth Producer",
  video: {
    width: 1080,
    height: 1920,
    fps: 30,
    durationSec: 45,
    captionTopPercent: 75,
    captionFont: "Noto Serif SC",
    captionHighlightColor: "#ffd84d",
  },
  captions: {
    highlightTerms: ["前 2 秒", "前 5 秒", "imagegen", "Remotion", "发布版"],
    data: [
      {
        startMs: 0,
        endMs: 3600,
        text: "前 2 秒如果没有主体画面，观众会直接划走。",
      },
      {
        startMs: 3600,
        endMs: 7600,
        text: "发布版必须先生成 imagegen 素材，再进入 Remotion。",
      },
      {
        startMs: 7600,
        endMs: 11800,
        text: "字幕固定在屏幕 75% 的位置，重点词用黄色。",
      },
      {
        startMs: 11800,
        endMs: 17000,
        text: "每 3 到 5 秒要换一次主画面结构。",
      },
      {
        startMs: 17000,
        endMs: 23000,
        text: "没有图片大模型时，只能做 Remotion-only 预览。",
      },
      {
        startMs: 23000,
        endMs: 31000,
        text: "发布版必须通过 manifest 和 visual plan 双重校验。",
      },
      {
        startMs: 31000,
        endMs: 45000,
        text: "这样别人下载 Skill 后，生成流程才不会自由发挥。",
      },
    ],
  },
  visualPlan: {
    beats: [
      {
        startSec: 0,
        endSec: 4,
        layout: "wrong-right",
        title: "0-2 秒不能空",
        subtitle: "主体画面必须立刻出现",
        visualGoal: "Show a concrete wrong-vs-right opening instead of an empty atmosphere.",
        assetSource: "generated-ui",
        bullets: ["空背景 = 划走", "对比/结果 = 留下"],
        motion: ["split reveal", "warning flash", "right-card lift"],
      },
      {
        startSec: 4,
        endSec: 9,
        layout: "workflow",
        title: "发布版流程",
        subtitle: "文案 → imagegen → Remotion → 校验",
        visualGoal: "Show the required production pipeline.",
        assetSource: "generated-ui",
        bullets: ["文案", "图片素材", "动态模板", "质检"],
        motion: ["step highlight", "connector sweep"],
      },
      {
        startSec: 9,
        endSec: 15,
        layout: "checklist",
        title: "字幕规则写死",
        visualGoal: "Show caption style requirements.",
        assetSource: "generated-ui",
        bullets: ["75% 位置", "白字黑阴影", "重点词黄色"],
        motion: ["caption lock", "keyword pop"],
      },
      {
        startSec: 15,
        endSec: 22,
        layout: "proof",
        title: "没有 imagegen",
        subtitle: "不能冒充发布级视频",
        visualGoal: "Explain strict mode blocking behavior.",
        assetSource: "generated-ui",
        bullets: ["Strict: 停止", "Remotion-only: 预览"],
        motion: ["mode switch", "lock icon"],
      },
      {
        startSec: 22,
        endSec: 32,
        layout: "asset-focus",
        title: "每期都要有视觉资产",
        visualGoal: "Show that generated visuals are mandatory in strict mode.",
        assetSource: "generated-ui",
        bullets: ["主视觉", "场景图", "封面底图"],
        motion: ["asset stack", "zoom scan"],
      },
      {
        startSec: 32,
        endSec: 45,
        layout: "cta",
        title: "先过校验，再导出",
        subtitle: "让 Skill 像生产线一样稳定",
        visualGoal: "Close with the quality gate.",
        assetSource: "generated-ui",
        bullets: ["manifest", "visual plan", "ffprobe"],
        motion: ["final checklist"],
      },
    ],
  },
};
